#!/bin/bash

if [ -z "${1}" ]; then
    echo "Should specify which spike to launch"
    exit 1
else
    is_image_present() {
        [ $(docker images | grep -c ${1}) -eq 1 ];
    }

    if is_image_present garagebcn/${1}; then
        echo "No build"
    else
        echo "Build required"
        docker build -t garagebcn/${1} ${1}
    fi

    if [ -f ${1}/run_opts ]; then
        . ${1}/run_opts
    fi

    docker run -d ${OPTS} garagebcn/${1} python /${1}.py ${ARGS}
fi
